name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # needed for README badge updates
      pull-requests: write
      checks: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Lint check
        run: npm run lint

      - name: Build TypeScript
        run: npm run build

      - name: Run tests with coverage
        run: npm run coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          fail_ci_if_error: true
          verbose: true

      - name: Generate coverage badge
        run: |
          COVERAGE=$(npx coverage-percentage ./coverage/lcov.info)
          echo "Coverage: $COVERAGE%"
          BADGE_URL="https://img.shields.io/badge/coverage-${COVERAGE}%25-brightgreen"
          sed -i -E "s|!\[Coverage\]\(.*\)|![Coverage](${BADGE_URL})|" README.md

      - name: Add build status badge
        if: github.ref == 'refs/heads/main'
        run: |
          BADGE_URL="https://github.com/${{ github.repository }}/actions/workflows/ci.yml/badge.svg"
          sed -i -E "s|!\[CI\]\(.*\)|![CI](${BADGE_URL})|" README.md

      - name: Commit updated badges
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add README.md
          git commit -m "ci: update badges [skip ci]" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref_name }}
